Issue 8
ryancurrie/continuous-delivery pull request #9
Opened 2017-11-02 23:20 UTC by ryancurrie

2017-11-02 23:28 UTC, thebearingedge commented
No `.gif`?

2017-11-03 17:15 UTC, thebearingedge requested changes
Cool, just one tweak, and be sure to add your project config files (linter/sync.js/etc)

2017-11-03 17:15 UTC, thebearingedge commented on client/todo-form.js
> +    console.log(JSON.stringify(data))
You can remove console logs like this.

2017-11-03 17:22 UTC, ryancurrie commented
![todo-1](https://user-images.githubusercontent.com/1384299/32387157-d05c0684-c080-11e7-9457-47f486c5b897.gif)

2017-11-03 17:44 UTC, thebearingedge requested changes
Please remove extra console logs.

2017-11-03 18:19 UTC, thebearingedge approved these changes

2017-11-03 18:21 UTC, merged